import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { AuthProvider } from "@/providers/AuthProvidor";
import GradientBackground from "./_components/background";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <AuthProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <GradientBackground>
              <Toaster
                position="top-right"
                toastOptions={{
                  style: {
                    fontSize: "14px",
                    padding: "12px 16px",
                    minWidth: "320px",
                    minHeight: "50px",
                    background: "#ecfdf5",
                    color: "#065f46",

                    borderRadius: "8px",
                    border: "1px solid #a7f3d0",

                    boxShadow: "0 4px 12px rgba(0,0,0,0.08)",
                  },
                  duration: 3000,
                }}
              />

              {children}
            </GradientBackground>
          </body>
        </AuthProvider>
      </html>
    </ClerkProvider>
  );
}
