import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignIn,
  SignInButton,
  UserButton,
  UserProfile,
} from "@clerk/nextjs";
import { Toaster } from "sonner";
import { AuthProvider } from "@/providers/AuthProvidor";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <AuthProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Toaster
              richColors
              position="top-right"
              toastOptions={{
                style: {
                  fontSize: "16px",
                  padding: "20px 24px",
                  minWidth: "420px",
                  minHeight: "80px",
                  background: "#00ba1c",
                  color: "white",
                  border: "2px solid #059669",
                  borderRadius: "12px",
                  boxShadow: "0 10px 25px rgba(16, 185, 129, 0.3)",
                  fontWeight: "500",
                },
                duration: 4000,
              }}
            />
            {children}
          </body>
        </AuthProvider>
      </html>
    </ClerkProvider>
  );
}
